### ISSUE TITLE
设置字体报错

### ISSUE THREAD

**Issue by winthesky** [pig-mesh/easy-captcha#4]
调用了`captcha.setFont(Captcha.FONT_1);`
发现`com.pig4cloud.captcha.base.Captcha.setFont`时报错
本地使用正常，在alpine中报错
![image](https://user-images.githubusercontent.com/3406410/143207753-655f0a89-5a10-4c20-a01c-db4d62cefca3.png)

**Comment by lltx** [comment]
检查你的机器的字体库是否完整
