### ISSUE TITLE
2.2.2版本ArithmeticCaptcha的supportAlgorithmSign()没看到除法的实现

### ISSUE THREAD

**Issue by Nan-qiu** [pig-mesh/easy-captcha#5]
作者在以后的版本会实现吗？
![image](https://user-images.githubusercontent.com/83400413/201477606-f53e438c-48bc-423f-a3d4-a11f268ead72.png)

**Comment by FULaBUla** [comment]
提交了除法的实现
https://github.com/pig-mesh/easy-captcha/pull/6
